language: go

go:
  - tip

install:
  - go get github.com/icza/gowut/gwu
  - go get github.com/udhos/lockfile
  - go get github.com/udhos/equalfile
  - go get github.com/udhos/difflib
  - go get gopkg.in/yaml.v2
  - go get golang.org/x/crypto/ssh
  - go get github.com/aws/aws-sdk-go/aws

script:
  - go install github.com/udhos/jazigo/jazigo
